export default {
  BEFORECREATE: 'BEFORECREATE',
  BEFOREMOUNT: 'BEFOREMOUNT',
  BEFOREDESTROY: 'BEFOREDESTROY',
  BEFOREUPDATE: 'BEFOREUPDATE',
  CREATED: 'CREATED',
  MOUNTED: 'MOUNTED',
  UPDATED: 'UPDATED',
  DESTROYED: 'DESTROYED',
  // vue lifecycle event
  BEFORELOGIN: 'BEFORELOGIN',
  LOGINED: 'LOGINED'
}
