export default {
  BEFORECREATE: 'BEFORECREATE',
  BEFOREMOUNT: 'BEFOREMOUNT',
  BEFOREDESTROY: 'BEFOREDESTROY',
  BEFOREUPDATE: 'BEFOREUPDATE',
  CREATED: 'CREATED',
  MOUNTED: 'MOUNTED',
  UPDATED: 'UPDATED',
  DESTROYED: 'DESTROYED',
  // vue lifecycle event
  BEFORELOGIN: 'BEFORELOGIN',
  LOGINED: 'LOGINED',
  MARKER_DRAGSTART: 'MARKER_DRAGSTART',
  MATERIAL_DRAGSTART: 'MATERIAL_DRAGSTART',
  MATERIAL_SELECTED: 'MATERIAL_SELECTED',
  MARKER_SELECTED: 'MARKER_SELECTED',
  MATERIAL_CLICK: 'MATERIAL_CLICK',
  MARKER_CLICK: 'MARKER_CLICK',
  MATERIAL_DBLCLICK: 'MATERIAL_DBLCLICK',
  MARKER_DBLCLICK: 'MARKER_DBLCLICK'
}
